set(PALABOS_ROOT "/home/murphyc/palabos")
set(BLOODFLOW_ROOT "/home/murphyc/BloodFlow")
set(LAMMPS_DIR "/home/murphyc/lammps")
set(CMAKE_C_COMPILER "mpicc" CACHE STRING "Specify the compiler to use")
set(CMAKE_CXX_STANDARD "11" CACHE STRING "Using c++11 version")
